Repository vitest-dev/vitest, pull requests merged in 2022-02, with the labels that each got.

#643 fix: update spy type inference
  packages/vitest/src/integrations/jest-mock.ts
  test/core/test/spy.test.ts
Labels: bug

#669 feat: add `allowOnly` option
  docs/guide/index.md
  package.json
  packages/ui/client/components/StatusIcon.vue
  packages/vitest/src/node/cli.ts
  packages/vitest/src/runtime/collect.ts
  packages/vitest/src/runtime/run.ts
  packages/vitest/src/types/config.ts
Labels: enhancement

#681 fix: avoid calling buildStart twice (fix #679)
  packages/vitest/src/node/create.ts
Labels: bug

#685 feat(ui): show all failed tasks in report
  packages/ui/client/components/views/ViewReport.vue
  packages/ui/client/styles/main.css
Labels: enhancement

#799 feat!: move config from `vitest/node` to `vitest/config`
  docs/config/index.md
  docs/guide/features.md
  docs/guide/index.md
  packages/vitest/package.json
  packages/vitest/rollup.config.js
  packages/vitest/src/config.ts
  packages/vitest/src/node/index.ts
  tsconfig.json
Labels: BEAKING CHANGE
