Repository vitest-dev/vitest, pull requests merged in 2022-01, with the labels that each got.

#531 feat: mocking timers with sinon
  docs/api/index.md
  docs/guide/debugging.md
  docs/guide/mocking.md
  packages/vitest/LICENSE.md
  packages/vitest/package.json
  packages/vitest/src/integrations/timers.ts
  packages/vitest/src/integrations/vi.ts
  pnpm-lock.yaml
  test/core/test/date-mock.test.ts
  test/core/test/timers.test.ts
  test/reporters/tests/reporters.spec.ts
Labels: BEAKING CHANGE

#632 docs: escape dot to prevent parsing of title as url
  docs/config/index.md
Labels: documentation

#635 feat(cli): add `--no-open` option
  docs/guide/index.md
  packages/vitest/src/node/cli.ts
  packages/vitest/src/node/plugins/index.ts
  packages/vitest/src/types/config.ts
Labels: enhancement

#633 fix: validate that nested and default tasks match `testNamePattern`
  packages/vitest/src/runtime/collect.ts
  test/core/test/test-name-pattern.test.ts
  test/core/vitest.config.ts
Labels: bug

#647 fix(ui): make graph data watch immediate
  packages/ui/client/components/FileDetails.vue
Labels: bug
