Repository vitest-dev/vitest, pull requests merged in 2022-09, with the labels that each got.

#1754 feat!: don't reset modules with --no-isolate
  packages/vitest/src/runtime/entry.ts
Labels: BREAKING CHANGE

#1803 feat!: if not processed, CSS Modules return a proxy, scope class names by filename
  docs/config/index.md
  packages/vitest/src/defaults.ts
  packages/vitest/src/integrations/css/css-modules.ts
  packages/vitest/src/node/config.ts
  packages/vitest/src/node/plugins/cssEnabler.ts
  packages/vitest/src/node/plugins/index.ts
  packages/vitest/src/types/config.ts
  pnpm-lock.yaml
  test/css/package.json
  test/css/src/App.css
  test/css/src/App.module.css
  test/css/test/default-css.spec.ts
  test/css/test/non-scope-module.spec.ts
  test/css/test/process-css.spec.ts
  test/css/test/process-module.spec.ts
  test/css/test/scope-module.spec.ts
  test/css/test/utils.ts
  test/css/testing.mjs
  test/css/vitest.config.ts
Labels: BREAKING CHANGE

#1029 feat: benchmark
  docs/config/index.md
  packages/ui/client/composables/summary.ts
  packages/vitest/package.json
  packages/vitest/src/defaults.ts
  packages/vitest/src/index.ts
  packages/vitest/src/node/cli-api.ts
  packages/vitest/src/node/cli.ts
  packages/vitest/src/node/config.ts
  packages/vitest/src/node/core.ts
  packages/vitest/src/node/create.ts
  packages/vitest/src/node/logger.ts
  packages/vitest/src/node/plugins/index.ts
  packages/vitest/src/node/reporters/benchmark/index.ts
  packages/vitest/src/node/reporters/benchmark/json.ts
  packages/vitest/src/node/reporters/index.ts
  packages/vitest/src/node/reporters/json.ts
  packages/vitest/src/node/reporters/renderers/listRenderer.ts
  packages/vitest/src/node/reporters/renderers/utils.ts
  packages/vitest/src/node/reporters/utils.ts
  packages/vitest/src/runtime/chain.ts
  packages/vitest/src/runtime/collect.ts
  packages/vitest/src/runtime/map.ts
  packages/vitest/src/runtime/run.ts
  packages/vitest/src/runtime/suite.ts
  packages/vitest/src/types/benchmark.ts
  packages/vitest/src/types/config.ts
  packages/vitest/src/types/index.ts
  packages/vitest/src/types/tasks.ts
  packages/vitest/src/utils/config-helpers.ts
  packages/vitest/src/utils/index.ts
  packages/vitest/src/utils/tasks.ts
  pnpm-lock.yaml
  test/benchmark/package.json
  test/benchmark/test/base.bench.ts
  test/benchmark/vitest.config.ts
  test/css/testing.mjs
Labels: BREAKING CHANGE, significant

#1972 fix(ui): display correct line and column for web UI
  packages/ui/client/components/views/ViewReport.cy.tsx
  packages/ui/client/components/views/ViewReport.vue
Labels: ui
