Repository vitest-dev/vitest, pull requests merged in 2024-12, with the labels that each got.

#6426 feat!: `spy.mockReset` changes
  docs/api/mock.md
  docs/api/vi.md
  docs/config/index.md
  docs/guide/migration.md
  packages/mocker/src/automocker.ts
  packages/spy/src/index.ts
  packages/vitest/src/integrations/vi.ts
  test/core/test/jest-mock.test.ts
Labels: breaking change

#6957 fix(coverage): correct coverage when `isolate: false` is used
  packages/browser/src/client/tester/tester.ts
  packages/coverage-istanbul/src/index.ts
  packages/coverage-v8/src/browser.ts
  packages/coverage-v8/src/index.ts
  packages/vitest/src/integrations/coverage.ts
  packages/vitest/src/node/types/coverage.ts
  packages/vitest/src/runtime/runBaseTests.ts
  packages/vitest/src/runtime/runVmTests.ts
  test/coverage-test/fixtures/setup.isolation.ts
  test/coverage-test/fixtures/src/branch.ts
  test/coverage-test/fixtures/test/isolation-1-fixture.test.ts
  test/coverage-test/fixtures/test/isolation-2-fixture.test.ts
  test/coverage-test/test/isolation.test.ts
  test/coverage-test/utils.ts
  test/coverage-test/vitest.config.ts
  test/coverage-test/vitest.workspace.custom.ts
Labels: cr-tracked

#5876 fix(expect)!: check more properties for error equality
  docs/api/expect.md
  packages/expect/src/jest-expect.ts
  packages/expect/src/jest-utils.ts
  packages/pretty-format/src/index.ts
  packages/utils/src/diff/index.ts
  test/core/test/__snapshots__/jest-expect.test.ts.snap
  test/core/test/expect.test.ts
  test/core/test/jest-expect.test.ts
Labels: breaking change

#6931 feat(runner): add "queued" state
  packages/browser/src/client/tester/runner.ts
  packages/browser/src/node/rpc.ts
  packages/browser/src/node/types.ts
  packages/runner/src/collect.ts
  packages/runner/src/run.ts
  packages/runner/src/types/tasks.ts
  packages/runner/src/utils/collect.ts
  packages/vitest/src/node/pools/rpc.ts
  packages/vitest/src/node/reporters/base.ts
  packages/vitest/src/node/reporters/benchmark/table/index.ts
  packages/vitest/src/node/reporters/default.ts
  packages/vitest/src/node/reporters/json.ts
  packages/vitest/src/node/reporters/renderers/utils.ts
  packages/vitest/src/node/reporters/reported-tasks.ts
  packages/vitest/src/node/reporters/summary.ts
  packages/vitest/src/node/reporters/task-parser.ts
  packages/vitest/src/node/reporters/verbose.ts
  packages/vitest/src/node/types/reporter.ts
  packages/vitest/src/runtime/runners/benchmark.ts
  packages/vitest/src/runtime/runners/index.ts
  packages/vitest/src/runtime/runners/test.ts
  packages/vitest/src/typecheck/collect.ts
  packages/vitest/src/typecheck/typechecker.ts
  packages/vitest/src/types/rpc.ts
  test/reporters/fixtures/long-loading-task.test.ts
  test/reporters/tests/default.test.ts
Labels: cr-tracked

#6974 feat(expect): add `toBeOneOf` matcher
  docs/api/expect.md
  packages/expect/src/custom-matchers.ts
  packages/expect/src/jest-extend.ts
  packages/expect/src/types.ts
  test/core/test/__snapshots__/jest-expect.test.ts.snap
  test/core/test/jest-expect.test.ts
Labels: p2-nice-to-have

#7115 fix(browser): fix provider options types
  packages/browser/providers/playwright.d.ts
  packages/browser/providers/webdriverio.d.ts
  test/dts-playwright/src/basic.test.ts
  test/dts-playwright/tsconfig.json
  test/dts-playwright/vite.config.ts
Labels: cr-tracked

#7019 fix: rewrite benchmark reporter without `log-update`
  packages/vitest/LICENSE.md
  packages/vitest/package.json
  packages/vitest/src/node/core.ts
  packages/vitest/src/node/error.ts
  packages/vitest/src/node/logger.ts
  packages/vitest/src/node/reporters/base.ts
  packages/vitest/src/node/reporters/benchmark/index.ts
  packages/vitest/src/node/reporters/benchmark/json-formatter.ts
  packages/vitest/src/node/reporters/benchmark/reporter.ts
  packages/vitest/src/node/reporters/benchmark/table/index.ts
  packages/vitest/src/node/reporters/benchmark/tableRender.ts
  packages/vitest/src/node/reporters/benchmark/verbose.ts
  packages/vitest/src/node/reporters/dot.ts
  packages/vitest/src/node/reporters/renderers/utils.ts
  packages/vitest/src/node/reporters/renderers/windowedRenderer.ts
  packages/vitest/src/node/reporters/verbose.ts
  packages/vitest/src/node/stdin.ts
  packages/vitest/src/runtime/runners/benchmark.ts
  pnpm-lock.yaml
  test/benchmark/fixtures/reporter/multiple.bench.ts
  test/benchmark/test/basic.test.ts
  test/benchmark/test/compare.test.ts
  test/benchmark/test/reporter.test.ts
  test/browser/specs/benchmark.test.ts
  test/browser/vitest.config.unit.mts
  test/config/test/console-color.test.ts
  test/config/test/exec-args.test.ts
  test/test-utils/cli.ts
  test/test-utils/index.ts
Labels: cr-tracked

#7133 fix(diff): truncate to avoid crash on diff large objects
  packages/utils/src/diff/index.ts
  test/core/test/diff.test.ts
Labels: cr-tracked

#7097 chore(deps)!: update fake-timers to v14.0.0
  package.json
  packages/vitest/LICENSE.md
  packages/vitest/package.json
  packages/vitest/src/integrations/mock/timers.ts
  packages/vitest/src/runtime/runVmTests.ts
  packages/vitest/src/runtime/setup-node.ts
  patches/@sinonjs__fake-timers@14.0.0.patch
  patches/@types__sinonjs__fake-timers@8.1.5.patch
  pnpm-lock.yaml
  test/core/test/fixtures/timers.suite.ts
Labels: p2-to-be-discussed, cr-tracked
