Repository vitest-dev/vitest, pull requests merged in 2025-06, with the labels that each got.

#7780 fix(spy): copy over static properties from the function
  packages/spy/package.json
  packages/spy/src/index.ts
  pnpm-lock.yaml
  test/core/package.json
  test/core/test/jest-mock.test.ts
  test/core/test/spy.test.ts
  test/reporters/tests/import-durations.test.ts
Labels: p2-to-be-discussed

#7884 fix!: remove `'basic'` reporter
  docs/advanced/reporters.md
  docs/guide/cli-generated.md
  docs/guide/migration.md
  docs/guide/reporters.md
  packages/vitest/src/node/reporters/basic.ts
  packages/vitest/src/node/reporters/index.ts
  packages/vitest/src/node/reporters/utils.ts
  packages/vitest/src/public/reporters.ts
  test/config/test/retry.test.ts
  test/core/test/exports.test.ts
  test/reporters/tests/configuration-options.test-d.ts
  test/watch/test/reporter-failed.test.ts
Labels: breaking change, feat: reporters

#7837 fix!(coverage): remove `.all`, reworked `include/exclude`
  docs/advanced/api/vitest.md
  docs/config/index.md
  docs/guide/cli-generated.md
  docs/guide/coverage.md
  docs/guide/migration.md
  packages/coverage-istanbul/package.json
  packages/coverage-istanbul/src/provider.ts
  packages/coverage-v8/package.json
  packages/coverage-v8/src/provider.ts
  packages/vitest/src/defaults.ts
  packages/vitest/src/node/cli/cli-config.ts
  packages/vitest/src/node/config/resolveConfig.ts
  packages/vitest/src/node/coverage.ts
  packages/vitest/src/node/types/coverage.ts
  pnpm-lock.yaml
  test/config/fixtures/coverage-test/example.ts
  test/config/test/failures.test.ts
  test/config/test/public.test.ts
  test/core/test/cli-test.test.ts
  test/coverage-test/test/all.test.ts
  test/coverage-test/test/allow-external.test.ts
  test/coverage-test/test/bundled-sources.test.ts
  test/coverage-test/test/changed.test.ts
  test/coverage-test/test/configuration-options.test-d.ts
  test/coverage-test/test/decorators.test.ts
  test/coverage-test/test/dynamic-files.test.ts
  test/coverage-test/test/empty-coverage-directory.test.ts
  test/coverage-test/test/exclude-after-remap.test.ts
  test/coverage-test/test/file-outside-vite.test.ts
  test/coverage-test/test/ignore-hints.test.ts
  test/coverage-test/test/implicit-else.istanbul.test.ts
  test/coverage-test/test/import-attributes.test.ts
  test/coverage-test/test/in-source.test.ts
  test/coverage-test/test/include-exclude.test.ts
  test/coverage-test/test/isolation.test.ts
  test/coverage-test/test/merge-reports.test.ts
  test/coverage-test/test/mocking-in-js-file.test.ts
  test/coverage-test/test/multi-environment.test.ts
  test/coverage-test/test/multi-suite.test.ts
  test/coverage-test/test/multi-transform.test.ts
  test/coverage-test/test/on-failure.test.ts
  test/coverage-test/test/pre-transpiled-source.test.ts
  test/coverage-test/test/reporters.test.ts
  test/coverage-test/test/setup-files.test.ts
  test/coverage-test/test/test-reporter-conflicts.test.ts
  test/coverage-test/test/threshold-auto-update.test.ts
  test/coverage-test/test/threshold-failure.test.ts
  test/coverage-test/test/threshold-glob.test.ts
  test/coverage-test/test/vue.test.ts
  test/coverage-test/test/workspace.multi-transform.test.ts
Labels: breaking change, feat: coverage, cr-tracked

#6287 feat!: simplify default exclude pattern
  docs/config/index.md
  docs/guide/improving-performance.md
  packages/vitest/src/defaults.ts
  packages/vitest/src/node/types/config.ts
  test/cli/fixtures/dotted-files/.cache/projects/test/.cache/should-not-run.test.ts
Labels: breaking change

#7963 fix(snapshot)!: fail test with obsolete snapshot on CI
  packages/runner/src/run.ts
  packages/vitest/src/runtime/runners/test.ts
  test/snapshots/test/fixtures/obsolete/src/__snapshots__/test1.test.ts.snap
  test/snapshots/test/fixtures/obsolete/src/__snapshots__/test2.test.ts.snap
  test/snapshots/test/fixtures/obsolete/src/test1.test.ts
  test/snapshots/test/fixtures/obsolete/src/test2.test.ts
  test/snapshots/test/fixtures/obsolete/vitest.config.ts
  test/snapshots/test/obsolete.test.ts
Labels: breaking change

#6160 fix(spy)!: support spying on classes
  docs/api/vi.md
  docs/guide/migration.md
  docs/guide/mocking.md
  packages/spy/src/index.ts
  test/cli/test/scoped-fixtures.test.ts
  test/core/test/jest-mock.test.ts
  test/core/test/spy.test.ts
Labels: breaking change
