Repository vitest-dev/vitest, pull requests merged in 2025-05, with the labels that each got.

#7703 docs: deprecate old context augmentation and recommend test.extend
  docs/advanced/runner.md
  docs/api/index.md
  docs/guide/cli-generated.md
  docs/guide/test-context.md
  packages/runner/src/types/tasks.ts
  test/cli/fixtures/fails/skip-conditional.test.ts
  test/core/test/on-finished.test.ts
  test/reporters/fixtures/default/a.test.ts
Labels: p2-to-be-discussed

#7896 fix(browser): resolve FS commands relative to the project root
  docs/guide/browser/commands.md
  packages/browser/src/node/commands/fs.ts
Labels: p2-nice-to-have

#7878 feat: provide `ctx.signal`
  docs/guide/test-context.md
  packages/browser/src/client/tester/runner.ts
  packages/browser/src/node/rpc.ts
  packages/browser/src/node/types.ts
  packages/runner/src/context.ts
  packages/runner/src/errors.ts
  packages/runner/src/hooks.ts
  packages/runner/src/run.ts
  packages/runner/src/suite.ts
  packages/runner/src/test-state.ts
  packages/runner/src/types/runner.ts
  packages/runner/src/types/tasks.ts
  packages/vitest/src/node/workspace/resolveWorkspace.ts
  packages/vitest/src/runtime/runBaseTests.ts
  packages/vitest/src/runtime/runVmTests.ts
  packages/vitest/src/runtime/runners/index.ts
  packages/vitest/src/runtime/runners/test.ts
  packages/vitest/src/types/global.ts
  test/cli/test/signal.test.ts
  test/core/vitest-environment-custom/index.ts
Labels: p2-nice-to-have

#7736 feat(coverage): v8 experimental AST-aware remapping
  docs/config/index.md
  docs/guide/coverage.md
  packages/coverage-v8/package.json
  packages/coverage-v8/src/provider.ts
  packages/vitest/src/node/types/coverage.ts
  pnpm-lock.yaml
  test/coverage-test/fixtures/src/ignore-hints.ts
  test/coverage-test/test/configuration-options.test-d.ts
  test/coverage-test/test/file-outside-vite.test.ts
  test/coverage-test/test/ignore-hints.test.ts
  test/coverage-test/utils.ts
  test/coverage-test/vitest.workspace.custom.ts
Labels: cr-tracked

#7927 feat: Explicit Resource Management support in mocked functions
  docs/api/vi.md
  packages/spy/src/index.ts
  test/core/test/jest-mock.test.ts
Labels: p2-nice-to-have

#7852 feat: add `sequence.groupOrder` option
  docs/config/index.md
  docs/guide/cli-generated.md
  packages/vitest/src/node/cli/cli-config.ts
  packages/vitest/src/node/config/resolveConfig.ts
  packages/vitest/src/node/pool.ts
  packages/vitest/src/node/types/config.ts
  test/cli/test/group-order.test.ts
Labels: p2-nice-to-have

#7016 fix: switch ExpectStatic `any` types to `AsymmetricMatcher<unknown>`, with `DeeplyAllowMatchers<T>`
  packages/expect/src/types.ts
  test/core/test/expect.test-d.ts
  test/core/test/vi.test-d.ts
  test/core/tsconfig.typecheck.json
  test/core/vite.config.ts
Labels: p2-nice-to-have

#7656 fix(@vitest/expect): support type-safe declaration of custom matchers
  docs/guide/extending-matchers.md
  packages/expect/src/types.ts
  packages/vitest/src/public/index.ts
  test/typescript/test-d/expect-extend.test-d.ts
Labels: p2-nice-to-have, cr-tracked

#7946 fix(coverage): browser + v8 in source tests missing
  packages/browser/src/node/plugin.ts
  packages/coverage-v8/src/browser.ts
  packages/coverage-v8/src/provider.ts
  test/coverage-test/fixtures/src/in-source.ts
  test/coverage-test/test/in-source.test.ts
  test/coverage-test/vitest.workspace.custom.ts
Labels: cr-tracked

#8021 fix(browser): await mocker invalidation to avoid race condition with "mock wasn't registered"
  packages/browser/src/node/providers/playwright.ts
  packages/mocker/src/browser/interceptor-msw.ts
  packages/mocker/src/browser/interceptor-native.ts
  packages/mocker/src/browser/interceptor.ts
  packages/mocker/src/browser/mocker.ts
Labels: cr-tracked

#8027 feat: track module execution totalTime and selfTime
  docs/advanced/api/test-module.md
  packages/runner/src/collect.ts
  packages/runner/src/types.ts
  packages/runner/src/types/runner.ts
  packages/runner/src/types/tasks.ts
  packages/vite-node/src/client.ts
  packages/vitest/src/node/reporters/reported-tasks.ts
  packages/vitest/src/public/index.ts
  packages/vitest/src/runtime/execute.ts
  packages/vitest/src/runtime/runners/test.ts
  test/cli/test/reported-tasks.test.ts
  test/reporters/fixtures/import-durations-25ms-throws.ts
  test/reporters/fixtures/import-durations-25ms.ts
  test/reporters/fixtures/import-durations-50ms.ts
  test/reporters/fixtures/import-durations-throws.test.ts
  test/reporters/fixtures/import-durations.test.ts
  test/reporters/tests/__snapshots__/html.test.ts.snap
  test/reporters/tests/html.test.ts
  test/reporters/tests/import-durations.test.ts
Labels: cr-tracked

#7704 feat(vitest): allow per-file and per-worker fixtures
  docs/guide/test-context.md
  packages/browser/src/client/public/esm-client-injector.js
  packages/browser/src/client/tester/runner.ts
  packages/browser/src/client/tester/state.ts
  packages/browser/src/client/tester/tester.ts
  packages/browser/src/client/utils.ts
  packages/runner/src/context.ts
  packages/runner/src/fixture.ts
  packages/runner/src/hooks.ts
  packages/runner/src/run.ts
  packages/runner/src/suite.ts
  packages/runner/src/types/runner.ts
  packages/runner/src/types/tasks.ts
  packages/runner/src/utils/collect.ts
  packages/vitest/src/node/pools/forks.ts
  packages/vitest/src/node/pools/threads.ts
  packages/vitest/src/node/pools/vmForks.ts
  packages/vitest/src/node/pools/vmThreads.ts
  packages/vitest/src/runtime/cleanup.ts
  packages/vitest/src/runtime/runVmTests.ts
  packages/vitest/src/runtime/runners/test.ts
  packages/vitest/src/runtime/worker.ts
  packages/vitest/src/types/global.ts
  packages/vitest/src/types/worker.ts
  test/cli/fixtures/custom-pool/pool/custom-pool.ts
  test/cli/test/scoped-fixtures.test.ts
  test/cli/vitest.config.ts
  test/reporters/src/data.ts
  test/reporters/tests/__snapshots__/reporters.spec.ts.snap
  test/reporters/tests/junit.test.ts
  test/test-utils/index.ts
Labels: p2-nice-to-have
