Repository vitest-dev/vitest, pull requests merged in 2025-03, with the labels that each got.

#7123 chore(deps): bump @types/chai to 5.0.1
  package.json
  packages/expect/package.json
  patches/@types__chai@4.3.6.patch
  patches/@types__chai@5.0.1.patch
  pnpm-lock.yaml
Labels: p2-to-be-discussed, cr-tracked

#7414 fix(runner): fix and simplify `Task.suite` initialization
  packages/runner/src/collect.ts
  packages/runner/src/suite.ts
  packages/runner/src/types/tasks.ts
  test/cli/fixtures/custom-runner/custom-runner.test.ts
  test/cli/fixtures/custom-runner/test-runner.ts
  test/cli/fixtures/custom-runner/utils.ts
  test/cli/fixtures/custom-runner/vitest.config.ts
  test/cli/test/custom-runner.test.ts
Labels: cr-tracked

#7557 fix(vite-node): fix source map of inlined node_modules
  eslint.config.js
  packages/vite-node/src/server.ts
  pnpm-lock.yaml
  test/cli/deps/error/index.js
  test/cli/deps/error/package.json
  test/cli/deps/error/transpiled-inline.js
  test/cli/deps/error/transpiled-inline.ts
  test/cli/deps/error/transpiled.js
  test/cli/deps/error/transpiled.js.map
  test/cli/deps/error/transpiled.ts
  test/cli/deps/error/ts.ts
  test/cli/fixtures/stacktraces/error-in-package.test.js
  test/cli/package.json
  test/cli/test/__snapshots__/stacktraces.test.ts.snap
  test/cli/test/stacktraces.test.ts
Labels: p3-minor-bug

#7531 fix: Race condition in RPC filesystem cache.
  packages/vitest/src/node/pools/rpc.ts
Labels: p2-to-be-discussed, cr-tracked

#7609 chore: use `unplugin-isolated-decl` with `oxc-transform` for dts build
  package.json
  packages/browser/rollup.config.js
  packages/coverage-istanbul/rollup.config.js
  packages/coverage-v8/rollup.config.js
  packages/expect/rollup.config.js
  packages/mocker/rollup.config.js
  packages/pretty-format/rollup.config.js
  packages/runner/rollup.config.js
  packages/snapshot/rollup.config.js
  packages/snapshot/src/port/state.ts
  packages/spy/rollup.config.js
  packages/ui/rollup.config.js
  packages/utils/rollup.config.js
  packages/vite-node/rollup.config.js
  packages/vitest/rollup.config.js
  packages/web-worker/rollup.config.js
  pnpm-lock.yaml
  scripts/build-utils.js
Labels: cr-tracked

#7481 feat: add `diff.maxDepth` option and set non-`Infinity` value as a default to reduce crash
  docs/config/index.md
  packages/utils/src/diff/index.ts
  packages/utils/src/diff/types.ts
  packages/vitest/src/node/cli/cli-config.ts
  test/core/test/diff.test.ts
Labels: cr-tracked

#7574 feat: Pass through vite configLoader option to createViteServer
  docs/.vitepress/scripts/cli-generator.ts
  docs/advanced/api/index.md
  docs/guide/cli-generated.md
  packages/browser/src/node/index.ts
  packages/vitest/src/node/cli/cli-api.ts
  packages/vitest/src/node/cli/cli-config.ts
  packages/vitest/src/node/create.ts
  packages/vitest/src/node/project.ts
  pnpm-lock.yaml
  test/cli/deps/linked/index.ts
  test/cli/deps/linked/package.json
  test/cli/fixtures/config-loader/browser/basic.test.ts
  test/cli/fixtures/config-loader/browser/vitest.config.ts
  test/cli/fixtures/config-loader/node/basic.test.ts
  test/cli/fixtures/config-loader/node/vitest.config.ts
  test/cli/fixtures/config-loader/vitest.config.ts
  test/cli/package.json
  test/cli/test/config-loader.test.ts
Labels: cr-tracked

#7705 feat: Added `vitest-browser-lit` to `vitest init browser` and docs
  docs/guide/browser/index.md
  packages/vitest/src/create/browser/creator.ts
  packages/vitest/src/create/browser/examples.ts
Labels: cr-tracked

#7697 fix: set `diff.expand: false` as default
  packages/utils/src/diff/normalizeDiffOptions.ts
  test/config/test/__snapshots__/diff.test.ts.snap
  test/config/test/diff.test.ts
  test/core/test/jest-expect.test.ts
Labels: p2-to-be-discussed
