Repository vitest-dev/vitest, pull requests merged in 2025-04, with the labels that each got.

#7783 fix(browser): fix transform error before browser server initialization
  packages/vitest/src/node/project.ts
  test/browser/vitest.config.mts
Labels: cr-tracked

#7763 fix(coverage): `await` profiler calls
  packages/coverage-v8/src/index.ts
Labels: cr-tracked

#7673 fix: default to run mode when stdin is not a TTY
  docs/config/index.md
  docs/guide/cli.md
  packages/vitest/src/defaults.ts
Labels: p2-to-be-discussed

#7795 fix: use happy-dom/jsdom types for `envionmentOptions`
  packages/vitest/optional-types.d.ts
  packages/vitest/rollup.config.js
  packages/vitest/src/integrations/env/jsdom.ts
  packages/vitest/src/types/happy-dom-options.ts
  packages/vitest/src/types/jsdom-options.ts
  test/dts-config/happy-dom-patch.ts
  test/dts-config/tsconfig.json
  test/dts-config/tsconfig.patch.json
  test/dts-fixture/tsconfig.check.json
  test/dts-fixture/tsconfig.json
  test/dts-playwright/tsconfig.json
Labels: cr-tracked

#6512 fix(browser): scale iframe for non ui case
  packages/browser/src/client/orchestrator.ts
  packages/browser/src/client/tester/locators/playwright.ts
  packages/browser/src/client/tester/utils.ts
  test/browser/fixtures/locators/blog.test.tsx
  test/browser/fixtures/viewport/basic.test.ts
  test/browser/fixtures/viewport/vitest.config.ts
  test/browser/specs/runner.test.ts
  test/browser/specs/viewport.test.ts
  test/browser/test/userEvent.test.ts
Labels: cr-tracked

#7665 perf(browser): improve browser parallelisation
  packages/browser/src/client/channel.ts
  packages/browser/src/client/client.ts
  packages/browser/src/client/orchestrator.ts
  packages/browser/src/client/public/error-catcher.js
  packages/browser/src/client/public/esm-client-injector.js
  packages/browser/src/client/tester/context.ts
  packages/browser/src/client/tester/logger.ts
  packages/browser/src/client/tester/runner.ts
  packages/browser/src/client/tester/state.ts
  packages/browser/src/client/tester/tester.ts
  packages/browser/src/client/tester/unhandled.ts
  packages/browser/src/client/utils.ts
  packages/browser/src/node/middlewares/testerMiddleware.ts
  packages/browser/src/node/plugin.ts
  packages/browser/src/node/pool.ts
  packages/browser/src/node/projectParent.ts
  packages/browser/src/node/providers/playwright.ts
  packages/browser/src/node/rpc.ts
  packages/browser/src/node/serverOrchestrator.ts
  packages/browser/src/node/serverTester.ts
  packages/browser/src/node/types.ts
  packages/expect/src/jest-expect.ts
  packages/vitest/src/node/browser/sessions.ts
  packages/vitest/src/node/types/browser.ts
  packages/vitest/src/public/index.ts
  packages/vitest/src/public/node.ts
  packages/vitest/src/runtime/config.ts
  packages/vitest/src/types/browser.ts
  packages/vitest/src/types/worker.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/browser/fixtures/browser-crash/vitest.config.ts
  test/browser/fixtures/mocking-out-of-root/project1/vitest.config.ts
  test/browser/setup.unit.ts
  test/browser/specs/browser-crash.test.ts
  test/browser/specs/setup-file.test.ts
  test/browser/specs/utils.ts
  test/browser/test/cdp.test.ts
  test/browser/vitest.config.mts
  test/core/test/__snapshots__/mocked.test.ts.snap
Labels: upstream, p3-significant, cr-tracked

#7864 chore(deps): unbundle tinyglobby and update
  package.json
  packages/vitest/LICENSE.md
  packages/vitest/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: cr-tracked
